-- =====================================================================
-- RENTFLOW — SUPABASE DATABASE MIGRATION SCRIPT
-- Run this in your Supabase Dashboard > SQL Editor > Click "Run"
-- =====================================================================

-- 1. Add Custom Columns to PROFILES table
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS phone TEXT,
  ADD COLUMN IF NOT EXISTS license_number TEXT,
  ADD COLUMN IF NOT EXISTS license_expiry DATE,
  ADD COLUMN IF NOT EXISTS license_id_url TEXT,
  ADD COLUMN IF NOT EXISTS address TEXT;

-- 2. Add Custom Columns to VEHICLES table
ALTER TABLE public.vehicles
  ADD COLUMN IF NOT EXISTS fuel_type TEXT DEFAULT 'Gasoline',
  ADD COLUMN IF NOT EXISTS has_ac BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS maintenance_days INT,
  ADD COLUMN IF NOT EXISTS maintenance_until TIMESTAMPTZ;

-- 2b. Add Reservation & Partial Payment Columns to BOOKINGS table
ALTER TABLE public.bookings
  ADD COLUMN IF NOT EXISTS paid_amount NUMERIC(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS balance_due NUMERIC(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS payment_type TEXT DEFAULT 'full',
  ADD COLUMN IF NOT EXISTS downpayment_percent INT DEFAULT 100;

-- 3. Create DRIVERS table
CREATE TABLE IF NOT EXISTS public.drivers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  phone TEXT,
  license_type TEXT DEFAULT 'Professional',
  experience_years INT DEFAULT 3,
  rating NUMERIC(3,2) DEFAULT 4.80,
  daily_fee NUMERIC(10,2) DEFAULT 500.00,
  status TEXT DEFAULT 'available' CHECK (status IN ('available', 'unavailable')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Seed initial sample drivers if not existing
INSERT INTO public.drivers (name, phone, license_type, experience_years, rating, daily_fee, status)
SELECT 'Ramon Santos', '+63 917 555 1024', 'Professional (Rest. 1,2,3)', 6, 4.90, 500.00, 'available'
WHERE NOT EXISTS (SELECT 1 FROM public.drivers WHERE name = 'Ramon Santos');

INSERT INTO public.drivers (name, phone, license_type, experience_years, rating, daily_fee, status)
SELECT 'Eduardo Reyes', '+63 918 444 8812', 'Professional Heavy', 8, 4.85, 500.00, 'available'
WHERE NOT EXISTS (SELECT 1 FROM public.drivers WHERE name = 'Eduardo Reyes');

-- Update any existing drivers to 500.00 daily fee
UPDATE public.drivers SET daily_fee = 500.00 WHERE daily_fee < 500.00;

-- 4. Create DRIVER_ASSIGNMENTS table
CREATE TABLE IF NOT EXISTS public.driver_assignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id BIGINT REFERENCES public.bookings(id) ON DELETE CASCADE,
  driver_id BIGINT REFERENCES public.drivers(id) ON DELETE CASCADE,
  assigned_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Enable Row Level Security (RLS) & Policies for Drivers
ALTER TABLE public.drivers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.driver_assignments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow read access on drivers" ON public.drivers;
CREATE POLICY "Allow read access on drivers" ON public.drivers FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow write access on drivers" ON public.drivers;
CREATE POLICY "Allow write access on drivers" ON public.drivers FOR ALL USING (true);

DROP POLICY IF EXISTS "Allow read access on driver_assignments" ON public.driver_assignments;
CREATE POLICY "Allow read access on driver_assignments" ON public.driver_assignments FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow write access on driver_assignments" ON public.driver_assignments;
CREATE POLICY "Allow write access on driver_assignments" ON public.driver_assignments FOR ALL USING (true);

-- 6. Create SERVICE_HISTORY table
CREATE TABLE IF NOT EXISTS public.service_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vehicle_id BIGINT REFERENCES public.vehicles(id) ON DELETE CASCADE,
  service_type TEXT NOT NULL,
  service_status TEXT DEFAULT 'in_service' CHECK (service_status IN ('in_service', 'scheduled', 'completed')),
  description TEXT,
  cost NUMERIC(10,2) DEFAULT 0.00,
  serviced_by TEXT,
  start_date DATE DEFAULT CURRENT_DATE,
  completion_date DATE,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.service_history ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow read access on service_history" ON public.service_history;
CREATE POLICY "Allow read access on service_history" ON public.service_history FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow write access on service_history" ON public.service_history;
CREATE POLICY "Allow write access on service_history" ON public.service_history FOR ALL USING (true);

-- 7. Fix CHECK constraints on bookings and vehicles tables for refund & maintenance statuses
ALTER TABLE public.bookings DROP CONSTRAINT IF EXISTS bookings_status_check;
ALTER TABLE public.bookings ADD CONSTRAINT bookings_status_check CHECK (
  status IN ('pending', 'approved', 'rejected', 'active', 'completed', 'cancelled', 'refund_requested', 'refunded')
);

ALTER TABLE public.vehicles DROP CONSTRAINT IF EXISTS vehicles_status_check;
ALTER TABLE public.vehicles ADD CONSTRAINT vehicles_status_check CHECK (
  status IN ('available', 'rented', 'maintenance', 'in_service', 'scheduled_maint', 'off_the_road')
);
