-- =====================================================================
-- REVIEWS & RATINGS TABLE FOR ONLINE VEHICLE RENTAL WEBSITE
-- Run this in Supabase Dashboard -> SQL Editor -> New query -> Click "Run"
-- =====================================================================

CREATE TABLE IF NOT EXISTS public.reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id BIGINT REFERENCES public.bookings(id) ON DELETE CASCADE,
  vehicle_id BIGINT NOT NULL REFERENCES public.vehicles(id) ON DELETE CASCADE,
  customer_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  rating INT NOT NULL CHECK (rating >= 1 AND rating <= 5),
  title TEXT,
  comment TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

-- Allow public read access to all verified reviews
DROP POLICY IF EXISTS "Allow public read reviews" ON public.reviews;
CREATE POLICY "Allow public read reviews"
  ON public.reviews FOR SELECT
  USING (true);

-- Allow authenticated users to insert reviews for their own completed bookings
DROP POLICY IF EXISTS "Allow customers insert reviews" ON public.reviews;
CREATE POLICY "Allow customers insert reviews"
  ON public.reviews FOR INSERT
  WITH CHECK (auth.uid() = customer_id);
